# Generated by Django 4.1.3 on 2022-11-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="ano",
            field=models.IntegerField(),
        ),
    ]
