# Generated by Django 4.1.3 on 2022-11-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_carro_quilometragem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=24)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
