# Generated by Django 4.1.3 on 2022-11-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_cliente"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cliente",
        ),
    ]
