# Generated by Django 4.1.3 on 2022-11-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_delete_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254)),
                ("celular", models.CharField(max_length=12)),
                ("cpf", models.CharField(max_length=12)),
            ],
        ),
    ]
