# Generated by Django 4.1.3 on 2022-11-22 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("AG PGTO", "Ag. Pgto"),
                            ("CANCELADO", "Cancelado"),
                            ("FINALIZADO", "Finalizado"),
                            ("PAUSADO", "Pausado"),
                        ],
                        default="ATIVO",
                        max_length=10,
                    ),
                ),
                ("descricao", models.TextField()),
                ("observacao", models.TextField()),
                ("mao_obra", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.cliente"
                    ),
                ),
                (
                    "itens",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
        ),
    ]
