# Generated by Django 4.1.3 on 2022-12-03 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_ordemservico"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="ts_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="ts_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
